In [2]:
#1. Create a new file named model_evaluation.py or model_evaluation.ipynb for these exercises.
import pandas as pd
from sklearn.metrics import confusion_matrix
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
from pydataset import data
from sklearn.metrics import precision_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report

In [9]:
#2. Given the following confusion matrix, evaluate (by hand) the model's performance.

'''
|               | pred dog   | pred cat   |
|:------------  |-----------:|-----------:|
| actual dog    |         46 |         7  |
| actual cat    |         13 |         34 |
'''
data = {'predicted_dog':[46,13],'predicted_cat':[7,34]}
df = pd.DataFrame(data,index=['actual_dog','actual_cat'])
df

predicted_dog  predicted_cat
actual_dog             46              7
actual_cat             13             34

In [13]:
tp, fn, fp, tn = df.predicted_dog[0], df.predicted_cat[0], df.predicted_dog[1], df.predicted_cat[1]

print("True Positives", tp)
print("False Positives", fp)
print("False Negatives", fn)
print("True Negatives", tn)

print("-------------")

accuracy = (tp + tn) / (tp + tn + fp + fn)
recall = tp / (tp + fn)
precision = tp / (tp + fp)

print("Accuracy is", accuracy)
print("Recall is", recall)
print("Precision is", precision)

F1 = (2 * precision * recall)/(precision + recall)
print('F1 score is', F1)

True Positives 46
False Positives 13
False Negatives 7
True Negatives 34
-------------
Accuracy is 0.8
Recall is 0.8679245283018868
Precision is 0.7796610169491526
F1 score is 0.8214285714285715


In [ ]:
# In the context of this problem, what is a false positive?
# Actual cat but predicted dog

# In the context of this problem, what is a false negative?
# Actual dog but predicted cat

# How would you describe this model?
# high accuracy and recall and decent precision, F1 score is 82%. Pretty good model

In [19]:
#3. You are working as a datascientist working for Codeup Cody Creator (C3 for short), a rubber-duck manufacturing plant.

# Unfortunately, some of the rubber ducks that are produced will have defects. 
# Your team has built several models that try to predict those defects, and the data from their predictions can be found here.

#. Use the predictions dataset and pandas to help answer the following questions:
c3 = pd.read_csv('c3.csv')
c3

actual     model1     model2     model3
0    No Defect  No Defect     Defect  No Defect
1    No Defect  No Defect     Defect     Defect
2    No Defect  No Defect     Defect  No Defect
3    No Defect     Defect     Defect     Defect
4    No Defect  No Defect     Defect  No Defect
..         ...        ...        ...        ...
195  No Defect  No Defect     Defect     Defect
196     Defect     Defect  No Defect  No Defect
197  No Defect  No Defect  No Defect  No Defect
198  No Defect  No Defect     Defect     Defect
199  No Defect  No Defect  No Defect     Defect

[200 rows x 4 columns]

In [31]:
(c3.actual == c3.model1).mean(), (c3.actual == c3.model2).mean(), (c3.actual == c3.model3).mean()

(0.95, 0.56, 0.555)

In [32]:
'''
- An internal team wants to investigate the cause of the manufacturing defects. They tell you that they want to identify as many of the ducks
that have a defect as possible.
Which evaluation metric would be appropriate here? Which model would be the best fit for this use case?
'''
#Accuracy, model 1 has highest

y_actual = c3.actual
y_pred1 = c3.model1
y_pred2 = c3.model2
y_pred3 = c3.model3


print(classification_report(y_actual,y_pred1,labels=['No Defect','Defect']))

              precision    recall  f1-score   support

   No Defect       0.96      0.99      0.97       184
      Defect       0.80      0.50      0.62        16

    accuracy                           0.95       200
   macro avg       0.88      0.74      0.79       200
weighted avg       0.95      0.95      0.94       200



In [33]:
print(classification_report(y_actual,y_pred2,labels=['No Defect','Defect']))

              precision    recall  f1-score   support

   No Defect       0.94      0.56      0.70       184
      Defect       0.10      0.56      0.17        16

    accuracy                           0.56       200
   macro avg       0.52      0.56      0.44       200
weighted avg       0.87      0.56      0.66       200



In [34]:
print(classification_report(y_actual,y_pred3,labels=['No Defect','Defect']))

              precision    recall  f1-score   support

   No Defect       0.97      0.53      0.69       184
      Defect       0.13      0.81      0.23        16

    accuracy                           0.56       200
   macro avg       0.55      0.67      0.46       200
weighted avg       0.90      0.56      0.65       200



In [37]:
'''
- Recently several stories in the local news have come out highlighting customers who received a rubber duck with a defect, and portraying C3 in a bad light.
The PR team has decided to launch a program that gives customers with a defective duck a vacation to Hawaii. They need you to predict which ducks will have defects, 
but tell you the really don't want to accidentally give out a vacation package when the duck really doesn't have a defect. Which evaluation metric would be appropriate here?
Which model would be the best fit for this use case?
'''

#False positives are more costly so Precision, model 1 has highest precision

In [41]:
'''
#4. You are working as a data scientist for Gives You Paws ™, a subscription based service that shows you cute pictures of 
dogs or cats (or both for an additional fee).

At Gives You Paws, anyone can upload pictures of their cats or dogs. The photos are then put through a two step process.
First an automated algorithm tags pictures as 
either a cat or a dog (Phase I). Next, the photos that have been initially identified are put through another round of review, 
possibly with some human oversight, before being presented to the users (Phase II).
'''

# Several models have already been developed with the data, and you can find their results here.

# Given this dataset, use pandas to create a baseline model (i.e. a model that just predicts the most common class) and answer the following questions:
gives_you_paws = pd.read_csv('gives_you_paws.csv')
gives_you_paws.head()

actual model1 model2 model3 model4
0    cat    cat    dog    cat    dog
1    dog    dog    cat    cat    dog
2    dog    cat    cat    cat    dog
3    dog    dog    dog    cat    dog
4    cat    cat    cat    dog    dog

In [42]:
gives_you_paws.actual.value_counts()

dog    3254
cat    1746
Name: actual, dtype: int64

In [43]:
gives_you_paws['baseline_prediction'] = 'dog'
gives_you_paws.head(1)

actual model1 model2 model3 model4 baseline_prediction
0    cat    cat    dog    cat    dog                 dog

In [45]:
#a. In terms of accuracy, how do the various models compare to the baseline model? Are any of the models better than the baseline?
model1_accuracy = (gives_you_paws.actual == gives_you_paws.model1).mean()
model2_accuracy = (gives_you_paws.actual == gives_you_paws.model2).mean()
model3_accuracy = (gives_you_paws.actual == gives_you_paws.model3).mean()
model4_accuracy = (gives_you_paws.actual == gives_you_paws.model4).mean()
baseline_accuracy = (gives_you_paws.actual == gives_you_paws.baseline_prediction).mean()

print(f'model1 accuracy: {model1_accuracy:.2%}') #all models except 3 are better than baseline
print(f'model2 accuracy: {model2_accuracy:.2%}')
print(f'model3 accuracy: {model3_accuracy:.2%}')
print(f'model4 accuracy: {model4_accuracy:.2%}')
print(f'baseline accuracy: {baseline_accuracy:.2%}')

model1 accuracy: 80.74%
model2 accuracy: 63.04%
model3 accuracy: 50.96%
model4 accuracy: 74.26%
baseline accuracy: 65.08%


In [ ]:
#b. Suppose you are working on a team that solely deals with dog pictures. Which of these models would you recomend for Phase I? For Phase II?
#dog = positive, just want highest accuracy == model 1 for phase 1 model4 for phase2 (highest recall for predicting dog)

#c. Suppose you are working on a team that solely deals with cat pictures. Which of these models would you recomend for Phase I? For Phase II?


In [46]:
#5. Follow the links below to read the documentation about each function, then apply those functions to the data from the previous problem.
y_true = gives_you_paws.actual
y_pred1 = gives_you_paws.model1
y_pred2 = gives_you_paws.model2
y_pred3 = gives_you_paws.model3
y_pred4 = gives_you_paws.model4

accuracy_score(y_true, y_pred1), accuracy_score(y_true, y_pred2), accuracy_score(y_true, y_pred3), accuracy_score(y_true, y_pred4)

(0.8074, 0.6304, 0.5096, 0.7426)

In [50]:
recall_score(y_true, y_pred1,
            labels = ['cat','dog'],
            average = None), recall_score(y_true, y_pred2,
                                          labels = ['cat','dog'],
                                          average = None), recall_score(y_true, y_pred3,
                                                                        labels = ['cat','dog'],
                                                                        average = None), recall_score(y_true, y_pred4,
                                                                                                        labels = ['cat','dog'],
                                                                                                        average = None)

(array([0.81500573, 0.80331899]),
 array([0.8906071 , 0.49078058]),
 array([0.51145475, 0.50860479]),
 array([0.34536082, 0.95574677]))

In [51]:
precision_score(y_true, y_pred1,
            labels = ['cat','dog'],
            average = None), precision_score(y_true, y_pred2,
                                          labels = ['cat','dog'],
                                          average = None), precision_score(y_true, y_pred3,
                                                                        labels = ['cat','dog'],
                                                                        average = None), precision_score(y_true, y_pred4,
                                                                                                        labels = ['cat','dog'],
                                                                                                        average = None)

(array([0.68977218, 0.89002383]),
 array([0.48412204, 0.89317673]),
 array([0.35834671, 0.65988836]),
 array([0.80722892, 0.73124853]))

In [54]:
print(classification_report(y_true, y_pred1, labels = ['cat','dog']))
print('-----------------------------------------------------------')
print(classification_report(y_true, y_pred2, labels = ['cat','dog']))
print('-----------------------------------------------------------')
print(classification_report(y_true, y_pred3, labels = ['cat','dog']))
print('-----------------------------------------------------------')
print(classification_report(y_true, y_pred4, labels = ['cat','dog']))

              precision    recall  f1-score   support

         cat       0.69      0.82      0.75      1746
         dog       0.89      0.80      0.84      3254

    accuracy                           0.81      5000
   macro avg       0.79      0.81      0.80      5000
weighted avg       0.82      0.81      0.81      5000

-----------------------------------------------------------
              precision    recall  f1-score   support

         cat       0.48      0.89      0.63      1746
         dog       0.89      0.49      0.63      3254

    accuracy                           0.63      5000
   macro avg       0.69      0.69      0.63      5000
weighted avg       0.75      0.63      0.63      5000

-----------------------------------------------------------
              precision    recall  f1-score   support

         cat       0.36      0.51      0.42      1746
         dog       0.66      0.51      0.57      3254

    accuracy                           0.51      5000
   macro